In [99]:
# Import python libraries
import pandas as pd
import numpy as np
import requests
import json
import string
import copy
import os
from csv import reader
from datetime import datetime
from dotenv import load_dotenv, find_dotenv
from random import randint
from pandas import DataFrame
from pprint import pprint

In [54]:
# Load in the congress and senate csv
congress_data = open('/Users/margueriteroth/repos/vue-d3-dataviz-starter/jupyter_notebooks/data_aging_congress.csv')

congress_data = reader(congress_data)
congress_table = list(congress_data)

congress_df = pd.DataFrame(congress, columns=congress_table[0])
congress_df.head()

,congress,start_date,chamber,state_abbrev,party_code,bioname,bioguide_id,birthday,cmltv_cong,cmltv_chamber,age_days,age_years,generation
0,82,1951-01-03,House,ND,200,"AANDAHL, Fred George",A000001,1897-04-09,1,1,19626,53.7330595482546,Lost
1,80,1947-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,1,1,14106,38.6201232032854,Greatest
2,81,1949-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,2,2,14837,40.621492128679,Greatest
3,82,1951-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,3,3,15567,42.6201232032854,Greatest
4,83,1953-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,4,4,16298,44.621492128679,Greatest

In [69]:
congress_df['start_date'] = pd.to_datetime(congress_df['start_date'])
congress_df['start_year'] = congress_df['start_date'].dt.year
congress_df['age_years'] = pd.to_numeric(congress_df['age_years'], errors='coerce').astype(float)
congress_df.head()

,congress,start_date,chamber,state_abbrev,party_code,bioname,bioguide_id,birthday,cmltv_cong,cmltv_chamber,age_days,age_years,generation,start_year
0,82,1951-01-03,House,ND,200,"AANDAHL, Fred George",A000001,1897-04-09,1,1,19626,53.733060,Lost,1951
1,80,1947-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,1,1,14106,38.620123,Greatest,1947
2,81,1949-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,2,2,14837,40.621492,Greatest,1949
3,82,1951-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,3,3,15567,42.620123,Greatest,1951
4,83,1953-01-03,House,VA,100,"ABBITT, Watkins Moorman",A000002,1908-05-21,4,4,16298,44.621492,Greatest,1953

In [71]:
# Check the data type of the 'age_years' column
column_data_type = congress_df['age_years'].dtype
print(f"The data type of 'age_years' column is: {column_data_type}")

The data type of 'age_years' column is: float64

In [100]:
# Create a function to calculate median age for each year
def calculate_median_age(dataframe):
    return dataframe.groupby(['start_year'])['age_years'].median()

house_df = congress_df[congress_df['chamber'] == 'House']
senate_df = congress_df[congress_df['chamber'] == 'Senate']

house_dict = calculate_median_age(house_df).to_dict()
senate_dict = calculate_median_age(senate_df).to_dict()

pprint(house_dict)

{1919: 49.6673511293634,
 1921: 50.5872689938398,
 1923: 51.2717316906229,
 1925: 52.772073921971256,
 1927: 53.8781656399726,
 1929: 54.1848049281314,
 1931: 54.516084873374396,
 1933: 52.94592744695415,
 1935: 51.145790554414745,
 1937: 50.60643394934975,
 1939: 50.318959616700894,
 1941: 50.35318275154005,
 1943: 50.8172484599589,
 1945: 51.6851471594798,
 1947: 51.4592744695414,
 1949: 50.7268993839836,
 1951: 51.80150581793295,
 1953: 52.2217659137577,
 1955: 52.3696098562628,
 1957: 52.993839835729,
 1959: 51.3456536618754,
 1961: 52.4599589322382,
 1963: 50.980150581793254,
 1965: 49.9849418206708,
 1967: 50.621492128678995,
 1969: 51.5783709787817,
 1971: 51.66050650239565,
 1973: 50.78439425051335,
 1975: 49.78097193702945,
 1977: 49.5468856947296,
 1979: 49.326488706365495,
 1981: 48.5475701574264,
 1983: 48.36002737850785,
 1985: 49.0431211498973,
 1987: 49.6317590691307,
 1989: 50.279260780287444,
 1991: 51.9206023271732,
 1993: 50.7378507871321,
 1995: 50.714579055441504,
 1997: 51.45242984257355,
 1999: 52.4681724845996,
 2001: 53.7987679671458,
 2003: 54.9486652977413,
 2005: 55.96851471594795,
 2007: 56.4626967830253,
 2009: 57.15811088295685,
 2011: 57.13757700205335,
 2013: 57.242984257358,
 2015: 57.5414099931554,
 2017: 58.12731006160165,
 2019: 57.83162217659135,
 2021: 58.2751540041068,
 2023: 57.8398357289528}

In [101]:
pprint(senate_dict)

{1919: 56.840520191649546,
 1921: 57.3990417522245,
 1923: 58.5845311430527,
 1925: 57.5222450376454,
 1927: 57.596167008898,
 1929: 57.567419575633096,
 1931: 57.1498973305955,
 1933: 57.4592744695414,
 1935: 57.5687885010267,
 1937: 59.123887748117696,
 1939: 59.9123887748118,
 1941: 57.5468856947296,
 1943: 58.652977412731,
 1945: 56.8624229979466,
 1947: 56.2737850787132,
 1949: 56.353182751540004,
 1951: 55.1950718685832,
 1953: 56.699520876112246,
 1955: 58.0643394934976,
 1957: 58.227241615332005,
 1959: 57.4182067077344,
 1961: 57.80424366872,
 1963: 57.80424366872,
 1965: 58.6023271731691,
 1967: 59.0225872689938,
 1969: 56.1409993155373,
 1971: 55.83436002737855,
 1973: 54.6447638603696,
 1975: 54.6584531143053,
 1977: 53.144421629021195,
 1979: 52.655715263518104,
 1981: 51.68104038329915,
 1983: 52.821355236139595,
 1985: 53.6673511293634,
 1987: 53.8480492813142,
 1989: 54.6502395619439,
 1991: 56.517453798768,
 1993: 57.2922655715264,
 1995: 57.4674880219028,
 1997: 56.16290212183435,
 1999: 57.14852840520195,
 2001: 58.3134839151266,
 2003: 59.35249828884325,
 2005: 60.99383983572895,
 2007: 62.6036960985626,
 2009: 61.9466119096509,
 2011: 61.0609171800137,
 2013: 61.6235455167693,
 2015: 61.27446954140996,
 2017: 62.6009582477755,
 2019: 63.347022587269,
 2021: 64.2819986310746,
 2023: 65.264887063655}